# Generated by Django 5.0.6 on 2024-07-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_stocked',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
