# Generated by Django 5.0.6 on 2024-09-06 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_itemcart_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='itens',
        ),
        migrations.AddField(
            model_name='itemcart',
            name='cart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.cart'),
        ),
    ]
