# Generated by Django 5.0.6 on 2024-09-06 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_cart_itens_itemcart_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcart',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.cart'),
        ),
    ]
