# Generated by Django 5.0.6 on 2024-09-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_itemcart_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cart'),
        ),
    ]
